import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class AppColors {
  final Color transparent = const Color(0x00000000);
  final Color first = const Color(0xffff6600);
  final Color secondary = const Color(0xfffb8c00);
  final Color background = const Color(0xFFF3F4F6);
  final Color background2 = const Color(0xfff0f5f9);
  final Color white = const Color(0xffffffff);
  final Color black = const Color(0xff222222);
  final Color orange0p5 = const Color(0xFFFFF8F5);
  final Color orange4 = const Color(0xFFFFA726);
  final Color orange5 = const Color(0xFFFF8243);
  final Color orange6 = const Color(0xFFEF6C00);
  final Color orange = const Color(0xFFFF9800);
  final Color orange1 = const Color(0xFFFFEEE3);
  final Color lightGrey = const Color(0xffdedede);
  final Color lightGrey2 = const Color(0xFFEEEEEE);
  final Color lightGrey3 = const Color(0xfff3f4f6);
  final Color lightGrey4 = const Color(0xfff9fafb);
  final Color darkGrey = const Color(0xd1474747);
  final Color disabled = const Color(0xffe9e9e9);
  final Color lightPrimary = const Color(0xfffff7ed);
  final Color lightBackground = const Color(0xfff0f5f9);
  final Color error = const Color(0xfffe4242);
  final Color shadow = const Color(0x45000000);
  final Color textGrey = const Color(0xff4f4f4f);
  final Color collectionSoon = const Color(0xFF374151);
  final Color grey = const Color(0xFF9E9E9E);
  final Color grey0p5 = const Color(0xFFF3F3F3);
  final Color grey1 = const Color(0xFFF3F4F6);
  final Color grey2 = const Color(0xFFE5E7EB);
  final Color grey3 = const Color(0xFFD1D5DB);
  final Color grey4 = const Color(0xFF9398A1);
  final Color grey5 = const Color(0xff666B77);
  final Color grey6 = const Color(0xFF4B5563);
  final Color grey7 = const Color(0xFF374151);
  final Color grey8 = const Color(0xFF1F2937);
  final Color grey8p5 = const Color(0xFF303030);
  final Color grey9 = const Color(0xFF212121);
  final Color disabledText = const Color(0xff6f6f6f);
  final Color red50 = const Color(0xFFF5DDD8);
  final Color red = const Color(0xFFF44336);
  final Color red6 = const Color(0xFFF22F04);
  final Color lightRed = const Color(0xfffef2f2);
  final Color green0p5 = const Color(0xFFDCF4E5);
  final Color green1 = const Color(0xFFC8E6C9);
  final Color green5 = const Color(0xFF10B981);
  final Color greenTeal = const Color(0xff10b981);
  final Color darkGreen = const Color(0xff059669);
  final Color blue = const Color(0xff00a3ff);
  final Color blue0p5 = const Color(0xFFEFF6FF);
  final Color blue1 = const Color(0xFFBBDEFB);
  final Color blue2 = const Color(0xFFDBEAFE);
  final Color blue3 = const Color(0xFF001E37);
  final Color lightBlue6 = const Color(0xFF0284C7);
  final Color dashboardTextLabel = const Color(0xFF505050);
  final Color grayishDarkBlue = const Color(0xff29304d);
  final Color primary = const Color(0xff00a3ff);
  final Color indigo9 = const Color(0xff1A237E);
  final Color indigo0p5 = const Color(0xFFE8EAF6);
  final Color indigo1 = const Color(0xFFC5CAE9);
  final Color yellow0p5 = const Color(0xFFFFFDE7);
  final Color yellow = const Color(0xffffaa00);
  final Color violet = const Color(0xff673ab7);
  final Color violet0p5 = const Color(0xffF5F3FF);

  const AppColors();
}
